version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@spirosdb:5432/thedb
    volumes:
      - /home/spiros/repos/the:/app


  spirosdb:
    image: postgres
    volumes:
      - postgres-sql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thedb

volumes:
  postgres-sql: null
