"""init

Revision ID: 26f284e15403
Revises: 
Create Date: 2023-11-18 22:08:30.277167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f284e15403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('generated_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_generation_id'), 'text_generation', ['id'], unique=False)
    op.create_table('deep_sentiment_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('admiration', sa.Float(), nullable=True),
    sa.Column('amusement', sa.Float(), nullable=True),
    sa.Column('anger', sa.Float(), nullable=True),
    sa.Column('annoyance', sa.Float(), nullable=True),
    sa.Column('approval', sa.Float(), nullable=True),
    sa.Column('caring', sa.Float(), nullable=True),
    sa.Column('confusion', sa.Float(), nullable=True),
    sa.Column('curiosity', sa.Float(), nullable=True),
    sa.Column('desire', sa.Float(), nullable=True),
    sa.Column('disappointment', sa.Float(), nullable=True),
    sa.Column('disapproval', sa.Float(), nullable=True),
    sa.Column('disgust', sa.Float(), nullable=True),
    sa.Column('embarrassment', sa.Float(), nullable=True),
    sa.Column('excitement', sa.Float(), nullable=True),
    sa.Column('fear', sa.Float(), nullable=True),
    sa.Column('gratitude', sa.Float(), nullable=True),
    sa.Column('grief', sa.Float(), nullable=True),
    sa.Column('joy', sa.Float(), nullable=True),
    sa.Column('love', sa.Float(), nullable=True),
    sa.Column('nervousness', sa.Float(), nullable=True),
    sa.Column('optimism', sa.Float(), nullable=True),
    sa.Column('pride', sa.Float(), nullable=True),
    sa.Column('realization', sa.Float(), nullable=True),
    sa.Column('relief', sa.Float(), nullable=True),
    sa.Column('remorse', sa.Float(), nullable=True),
    sa.Column('sadness', sa.Float(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('neutral', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['text_generation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deep_sentiment_analysis_id'), 'deep_sentiment_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deep_sentiment_analysis_id'), table_name='deep_sentiment_analysis')
    op.drop_table('deep_sentiment_analysis')
    op.drop_index(op.f('ix_text_generation_id'), table_name='text_generation')
    op.drop_table('text_generation')
    # ### end Alembic commands ###
